
### Log in
POST http://localhost:3000/auth/login
content-type: application/json

{
    
    "email": "david@gmail.com",
    "password": "david@2006"
}


###create new account
POST http://localhost:3000/auth/register
content-type: application/json

{
    "username": "david",
    "email": "david@gmail.com",
    "password": "david@2006"
}

### Tsts
GET http://localhost:3000/auth/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiZGF2aWRAZ21haWwuY29tIiwiaWF0IjoxNzM2MzYwNTg2LCJleHAiOjE3MzYzNjQxODZ9.Sb8-8JZepLQq8kBu1cuBzLl6udr93jv6kThzdz3_0hc




###Log out
POST http://localhost:3000/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiZGF2aWRAZ21haWwuY29tIiwiaWF0IjoxNzM2MzYwMzQ3LCJleHAiOjE3MzYzNjM5NDd9.AO-uyP4ampnTa6NdkaC2S1W3yy2ZglJaE3m6sPdOFy4


###Create deadline task
POST http://localhost:3000/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiZGF2aWRAZ21haWwuY29tIiwiaWF0IjoxNzM2MzYwNTg2LCJleHAiOjE3MzYzNjQxODZ9.Sb8-8JZepLQq8kBu1cuBzLl6udr93jv6kThzdz3_0hc
content-type: application/json

{
    "title": "homework",
    "type": "DEADLINE",
    "deadline": "2025-01-20T09:00:00Z"



}

